//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Orchestrator.SafeguardSecureStoreTests {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UiPath.Orchestrator.SafeguardSecureStoreTests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string JsonDeserializationIssue {
            get {
                return ResourceManager.GetString("JsonDeserializationIssue", resourceCulture);
            }
        }
        
        internal static string SafeguardJsonInvalidOrMissing {
            get {
                return ResourceManager.GetString("SafeguardJsonInvalidOrMissing", resourceCulture);
            }
        }
        
        internal static string SafeguardReadOnly {
            get {
                return ResourceManager.GetString("SafeguardReadOnly", resourceCulture);
            }
        }
        
        internal static string SafeguardSettingInvalidOrMissing {
            get {
                return ResourceManager.GetString("SafeguardSettingInvalidOrMissing", resourceCulture);
            }
        }
        
        internal static string SettingSafeguardAppliance {
            get {
                return ResourceManager.GetString("SettingSafeguardAppliance", resourceCulture);
            }
        }
        
        internal static string SettingSafeguardCertificateThumprint {
            get {
                return ResourceManager.GetString("SettingSafeguardCertificateThumprint", resourceCulture);
            }
        }
        
        internal static string SettingIgnoreSSL {
            get {
                return ResourceManager.GetString("SettingIgnoreSSL", resourceCulture);
            }
        }
        
        internal static string SafeguardNoAccessToRetrievableCredentials {
            get {
                return ResourceManager.GetString("SafeguardNoAccessToRetrievableCredentials", resourceCulture);
            }
        }
    }
}
