//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Orchestrator.SafeguardSecureStore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.Orchestrator.SafeguardSecureStore.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json deserialization issue | json: {0} || appliance: {1} || thumbprint: {2} || ignoreSSL: {3}.
        /// </summary>
        internal static string JsonDeserializationIssue {
            get {
                return ResourceManager.GetString("JsonDeserializationIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safeguard json is invalid or is missing, context: {0}.
        /// </summary>
        internal static string SafeguardJsonInvalidOrMissing {
            get {
                return ResourceManager.GetString("SafeguardJsonInvalidOrMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function not implemented for read-only Safeguard Credential Store.
        /// </summary>
        internal static string SafeguardReadOnly {
            get {
                return ResourceManager.GetString("SafeguardReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing Safeguard setting || appliance= {0} thumbprint={1}  || ignoreSSL: {3}.
        /// </summary>
        internal static string SafeguardSettingInvalidOrMissing {
            get {
                return ResourceManager.GetString("SafeguardSettingInvalidOrMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Logging.
        /// </summary>
        internal static string SettingDebugLogging {
            get {
                return ResourceManager.GetString("SettingDebugLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not validate the SSL certificate of Safeguard (IgnoreSSL).
        /// </summary>
        internal static string SettingIgnoreSSL {
            get {
                return ResourceManager.GetString("SettingIgnoreSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safeguard Appliance.
        /// </summary>
        internal static string SettingSafeguardAppliance {
            get {
                return ResourceManager.GetString("SettingSafeguardAppliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate thumprint used to connect to Safeguard.
        /// </summary>
        internal static string SettingSafeguardCertificateThumprint {
            get {
                return ResourceManager.GetString("SettingSafeguardCertificateThumprint", resourceCulture);
            }
        }
    }
}
